### PR TITLE
Github releases API auth

### LINKED ISSUE #47: Heighliner hits Github rate limits
```
Oct 14 21:01:16 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:16 Error queueing docker image builds for chain tendermint: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
Oct 14 21:01:16 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:16 Error queueing docker image builds for chain terra: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
Oct 14 21:01:17 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:17 Error queueing docker image builds for chain thorchain: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
Oct 14 21:01:17 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:17 Error queueing docker image builds for chain umee: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
Oct 14 21:01:17 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:17 Error queueing docker image builds for chain vidulum: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
Oct 14 21:01:17 github-actions-heighliner buildLoop.sh[3535277]: 2022/10/14 21:01:17 Error queueing docker image builds for chain wasm: error parsing github releases response: {"message":"API rate limit exceeded for 104.197.32.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}, error: json: cannot unmarshal object into Go value of type []cmd.GithubRelease
```

### PR DESCRIPTION
**Pull request by agouin**
Unauthenticated requests are limited to 60 requests per hour. This increases to 1000 per hour per repo for personal accounts, and 15000 for enterprise accounts.

Adds `GH_USER` and `GH_PAT` env vars to authenticate to Github API when fetching recent releases

Resolves #47

### CODE REVIEW

File: cmd/queue.go [hunk 1]
```diff
@@ -36,6 +38,11 @@ func mostRecentReleasesForChain(
 		return builder.HeighlinerQueuedChainBuilds{}, fmt.Errorf("error building github releases request: %v", err)
 	}
 
+	githubUser, githubPAT := os.Getenv("GH_USER"), os.Getenv("GH_PAT")
+	if githubUser != "" && githubPAT != "" {
+		req.Header.Add("Authorization", "Basic "+base64.StdEncoding.EncodeToString([]byte(githubUser+":"+githubPAT)))
```
Comment (boojamya) [inline cmd/queue.go:43]: Sleek.

**Review by boojamya — APPROVED** [review]
